/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Card.java
 *
 * Created on Dec 13, 2011, 3:54:33 PM
 */
package com.gauronit.tagmata.views;

import com.gauronit.tagmata.Main;
import com.gauronit.tagmata.core.CardSnapshot;
import com.gauronit.tagmata.core.Indexer;
import javax.swing.JOptionPane;

/**
 *
 * @author jjayesh
 */
public class CardView extends javax.swing.JDialog {

    String indexDisplayName = null;
    String indexName = null;
    CardSnapshot cardSnap = null;

    /** Creates new form Card */
    public CardView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (cardSnap != null) {
            titleTxtBox.setText(cardSnap.getTitle());
            tagsTxtBox.setText(cardSnap.getTags());
            textTxtBox.setText(cardSnap.getText());
            indexName = cardSnap.getDoc().get("indexName");
            indexDisplayName = MainView.mainView.getIndexDisplayName(indexName);
            indexNameLbl.setText("Index Selected is '" + indexDisplayName + "'");
        } else {
            indexDisplayName = MainView.mainView.getSelectedIndexDisplayName();
            indexName = MainView.mainView.getSelectedIndexName();
            indexNameLbl.setText("Index Selected is '" + indexDisplayName + "'");
        }
    }

    public CardView(CardSnapshot cardSnap, java.awt.Frame parent, boolean modal) {
        this(parent, modal);
        this.cardSnap = cardSnap;
        if (cardSnap != null) {
            titleTxtBox.setText(cardSnap.getTitle());
            tagsTxtBox.setText(cardSnap.getTags());
            textTxtBox.setText(cardSnap.getText());
            indexName = cardSnap.getDoc().get("indexName");
            indexDisplayName = MainView.mainView.getIndexDisplayName(indexName);
            indexNameLbl.setText("Index Selected is '" + indexDisplayName + "'");
        } else {
            indexDisplayName = MainView.mainView.getSelectedIndexDisplayName();
            indexName = MainView.mainView.getSelectedIndexName();
            indexNameLbl.setText("Index Selected is '" + indexDisplayName + "'");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleTxtBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tagsTxtBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTxtBox = new javax.swing.JEditorPane();
        addBtn = new javax.swing.JButton();
        indexNameLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gauronit.tagmata.Main.class).getContext().getResourceMap(CardView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        titleTxtBox.setText(resourceMap.getString("titleTxtBox.text")); // NOI18N
        titleTxtBox.setName("titleTxtBox"); // NOI18N
        titleTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtBoxActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        tagsTxtBox.setText(resourceMap.getString("tagsTxtBox.text")); // NOI18N
        tagsTxtBox.setName("tagsTxtBox"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        textTxtBox.setName("textTxtBox"); // NOI18N
        jScrollPane1.setViewportView(textTxtBox);

        addBtn.setText(resourceMap.getString("addBtn.text")); // NOI18N
        addBtn.setName("addBtn"); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        indexNameLbl.setFont(resourceMap.getFont("indexNameLbl.font")); // NOI18N
        indexNameLbl.setText(resourceMap.getString("indexNameLbl.text")); // NOI18N
        indexNameLbl.setName("indexNameLbl"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                            .addComponent(tagsTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(indexNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tagsTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtBoxActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String title = titleTxtBox.getText().trim();
        String tags = tagsTxtBox.getText().trim();
        String text = textTxtBox.getText().trim();

        if (title.equals("") && tags.equals("") && text.equals("")) {
            JOptionPane.showMessageDialog(Main.getApplication().getMainFrame(), "Please enter at least one field to save.", "Saving a Card", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            if (cardSnap == null) {
                Indexer.currentInstance().saveCard(title, tags, text, indexName);
            } else {
                Indexer.currentInstance().updateCard(cardSnap, title, tags, text);
                MainView.mainView.fillResults();
                MainView.mainView.refreshBookmarks();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        this.dispose();
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CardView dialog = new CardView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel indexNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tagsTxtBox;
    private javax.swing.JEditorPane textTxtBox;
    private javax.swing.JTextField titleTxtBox;
    // End of variables declaration//GEN-END:variables
}
