/*******************************************************************************
 * Copyright (c) 2012, Gauronit, LLC.
 * All rights reserved. Tagmata and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     Jayesh J - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.22 at 05:37:14 PM IST 
//


package com.gauronit.tagmata.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gauronit.tagmata.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Text_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Text");
    private final static QName _Tags_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Tags");
    private final static QName _Action_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Action");
    private final static QName _Message_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Message");
    private final static QName _Id_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Id");
    private final static QName _Title_QNAME = new QName("http://www.gauronit.com/tagmata/schema", "Title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gauronit.tagmata.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SyncCardsResponse }
     * 
     */
    public SyncCardsResponse createSyncCardsResponse() {
        return new SyncCardsResponse();
    }

    /**
     * Create an instance of {@link FetchCardsRequest }
     * 
     */
    public FetchCardsRequest createFetchCardsRequest() {
        return new FetchCardsRequest();
    }

    /**
     * Create an instance of {@link FetchCardsResponse }
     * 
     */
    public FetchCardsResponse createFetchCardsResponse() {
        return new FetchCardsResponse();
    }

    /**
     * Create an instance of {@link RemoveSyncCardsRequest }
     * 
     */
    public RemoveSyncCardsRequest createRemoveSyncCardsRequest() {
        return new RemoveSyncCardsRequest();
    }

    /**
     * Create an instance of {@link RemoveSyncCardsResponse }
     * 
     */
    public RemoveSyncCardsResponse createRemoveSyncCardsResponse() {
        return new RemoveSyncCardsResponse();
    }

    /**
     * Create an instance of {@link SyncCardsRequest }
     * 
     */
    public SyncCardsRequest createSyncCardsRequest() {
        return new SyncCardsRequest();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Tags")
    public JAXBElement<String> createTags(String value) {
        return new JAXBElement<String>(_Tags_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gauronit.com/tagmata/schema", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
